name: MegaLinter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mega-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: 'false'
          OUTPUT_FORMAT: 'sarif'
          SARIF_REPORTER: 'true'
          SARIF_REPORTER_FILE_NAME: 'megalinter-report.sarif'

      - name: List generated reports for debugging
        run: ls -R

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'megalinter-reports/megalinter-report.sarif'
          
      - name: Upload SARIF report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: megalinter-report
          path: megalinter-reports/megalinter-report.sarif
