name: Semgrep
on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/semgrep.yaml
  schedule:
    - cron: '25 3 * * *'  # Scheduled runs.

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_KEY }}
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
      ENGAGEMENT_NAME: ${{ secrets.ENGAGEMENT_NAME }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - name: Run Semgrep scan
      id: semgrep
      run: semgrep --config auto --json . > semgrep_results.json

    - name: Upload Semgrep report to DefectDojo
      run: |
        # Debug: Print environment variables to ensure they are set correctly
        echo "DEFECT_DOJO_API_TOKEN: $DEFECT_DOJO_API_TOKEN"
        echo "DEFECTDOJO_URL: $DEFECTDOJO_URL"
        echo "PRODUCT_NAME: $PRODUCT_NAME"
        echo "ENGAGEMENT_NAME: $ENGAGEMENT_NAME"
        
        # Ensure that semgrep_results.json exists
        ls -la semgrep_results.json
        
        # Install required Python packages
        pip install requests
        
        # Export DEFECT_DOJO_API_TOKEN environment variable
        export DEFECT_DOJO_API_TOKEN=$DEFECT_DOJO_API_TOKEN
        
        # Run the Python script to upload the report
        python3 .github/workflows/upload_semgrep_to_defectdojo.py \
          --host $DEFECTDOJO_URL \
          --product $PRODUCT_NAME \
          --engagement $ENGAGEMENT_NAME \
          --report semgrep_results.json \
          --is_new_import
