name: Semgrep
on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/semgrep.yaml
  schedule:
    - cron: '25 3 * * *'  # Scheduled runs..

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - name: Run Semgrep scan
      id: semgrep
      run: semgrep --config auto --json . > semgrep_results.json

    - name: Upload Semgrep report to DefectDojo
      env:
        DEFECT_DOJO_API_TOKEN: "1b9c5ac045cfec60f3b508e969a6d3b7d3f52247"
        DEFECTDOJO_URL: "http://13.213.67.252:8080"
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
        ENGAGEMENT_NAME: ${{ secrets.ENGAGEMENT_NAME }}
      run: |
        pip install requests
        python3 .github/workflows/upload_semgrep_to_defectdojo.py \
          --host $DEFECTDOJO_URL \
          --product $PRODUCT_NAME \
          --engagement $ENGAGEMENT_NAME \
          --report semgrep_results.json \
          --is_new_import
