on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - release
    - master
    - develop
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 25 3 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - name: Run Semgrep scan
      id: semgrep
      run: semgrep --config auto --json . > semgrep_results.json

    - name: Upload Semgrep report to DefectDojo
      env:
        DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_KEY }}
        DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
        ENGAGEMENT_NAME: ${{ secrets.ENGAGEMENT_NAME }}
      run: |
        pip install requests
        python .github/workflows/upload_semgrep_to_defectdojo.py \
          --host $DEFECTDOJO_URL \
          --token $DEFECT_DOJO_API_TOKEN \
          --product $PRODUCT_NAME \
          --engagement $ENGAGEMENT_NAME \
          --report report.json \
          --is_new_import

