name: Lint Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Mega-Linter
      uses: oxsecurity/megalinter@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: master
        OUTPUT_FORMAT: sarif
        OUTPUT_FOLDER: /tmp/lint-reports

    - name: List contents of the output folder
      run: |
        ls -al /tmp/lint-reports
        pwd

    - name: Upload SARIF file
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: /tmp/lint-reports/megalinter-reports.sarif
