#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

######################################
# Trigger the job on push and pull requests #
######################################
on:
  push:
  pull_request:
    branches: [master, release, develop]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Cache the linter's dependencies #
      ##########################
      - name: Cache Linter Dependencies
        uses: actions/cache@v3
        with:
          path: /path/to/linter/cache
          key: linter-cache-${{ runner.os }}-${{ hashFiles('**/*.yml') }}
          restore-keys: |
            linter-cache-${{ runner.os }}-

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Only fetch the latest commit
          fetch-depth: 1

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          REPORT_OUTPUT: sarif
          OUTPUT_FOLDER: reports

      ##########################
      # Upload Linter findings to DefectDojo #
      ##########################
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install DefectDojo API Client
        run: pip install defectdojo_api

      - name: Upload to DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          import json
          from defectdojo_api import defectdojo

          # Initialize the DefectDojo connection
          dojo = defectdojo.DefectDojoAPI(
              host="${{ secrets.DEFECTDOJO_URL }}",
              api_token="${{ secrets.DEFECTDOJO_API_KEY }}",
              api_v2_key="${{ secrets.DEFECTDOJO_API_KEY }}",
              user="",
              verify_ssl=True
          )

          # Read the SARIF report
          report_path = 'reports/super-linter.sarif'
          try:
            with open(report_path, 'r') as report_file:
                report_content = json.load(report_file)

            # Upload the report
            response = dojo.upload_sarif(
                engagement_id=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }},
                file=report_content,
                scan_type='Sarif',
                active=True,
                verified=False
            )

            if response.success:
                print("Upload successful!")
            else:
                print(f"Upload failed: {response.message}")
          except Exception as e:
            print(f"Error reading or uploading report: {str(e)}")

