name: Mega Linter Analysis

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch

jobs:
  mega-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create lint-reports directory
      run: mkdir -p /tmp/lint-reports

    - name: Run Mega-Linter
      uses: oxsecurity/megalinter@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: master
        OUTPUT_FORMAT: sarif
        OUTPUT_FOLDER: /tmp/lint-reports
        SARIF_REPORTER: true  # Enable SARIF report generation
      continue-on-error: true

    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: /tmp/lint-reports/megalinter-report.sarif
