name: Super Linter

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  # Continue running job even after errors
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create reports folder
        run: mkdir reports
      
      - name: List files in reports folder before linting
        run: ls -l reports || true  # Use || true to prevent failure if folder doesn't exist
      
      - name: Run Super Linter
        id: super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          OUTPUT_FORMAT: json
          FAIL_ON_WARNINGS: false  # Continue on warnings as well
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save linter output to file
        if: ${{ always() }}  # Ensure this step runs even if previous steps fail
        run: |
          echo "${{ steps.super-linter.outputs.linter-output }}" > reports/linter-output.json
          cat reports/linter-output.json  # Display content for verification
      
      - name: List files in reports folder after linting
        run: ls -l reports || true  # Use || true to prevent failure if folder doesn't exist
