name: ESLint SARIF Report

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install ESLint and dependencies
        run: |
          npm install eslint@latest @babel/core @babel/eslint-parser @microsoft/eslint-formatter-sarif

      - name: Run ESLint with SARIF output
        run: npx eslint . --ext .js,.jsx -f @microsoft/eslint-formatter-sarif -o eslint-report.sarif || true

      - name: Verify ESLint SARIF report
        run: ls -l eslint-report.sarif || echo "ESLint SARIF report not found"

      - name: Upload ESLint SARIF report
        if: success() && steps.lint.outputs.exit-code == '0'
        uses: actions/upload-artifact@v2
        with:
          name: eslint-sarif-report
          path: eslint-report.sarif
