name: Lint and Upload to DefectDojo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v6
        with:
          linter_name: 'ALL'
          sarif: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          if [ -f report/super-linter.sarif ]; then
            curl -X POST -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -F "file=@report/super-linter.sarif" \
              $DEFECTDOJO_URL/api/v2/engagements/$DEFECTDOJO_ENGAGEMENT_ID/upload_sarif/
          else
            echo "SARIF report not found!"
          fi
