name: Super Linter

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create reports folder
        run: mkdir reports
      
      - name: List files in reports folder before linting
        run: ls -l reports
      
      - name: Run Super Linter
        id: super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          OUTPUT_FORMAT: json
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save linter output to file
        run: echo "${{ steps.super-linter.outputs.linter-output }}" > reports/linter-output.json
      
      - name: List files in reports folder after linting
        run: ls -l reports
