name: Super-Linter

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FORMAT: json

      - name: Verify JSON report exists
        run: ls -l lint-results/*.json

      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with:
          name: super-linter-results
          path: lint-results/*.json
