name: Lint and Upload to DefectDojo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Mega Linter
        run: |
          npm install -g mega-linter-runner

      - name: Run Mega Linter
        run: |
          mega-linter-runner --linter=ALL -s /github/workspace -d

      - name: Generate Dummy SARIF if not generated
        if: success()
        run: echo '{"version": "2.1.0","runs": []}' > /github/workspace/super-linter.sarif

      - name: Upload SARIF to DefectDojo
        if: success()
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          curl -X POST -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -F "file=@/github/workspace/super-linter.sarif" \
            $DEFECTDOJO_URL/api/v2/engagements/$DEFECTDOJO_ENGAGEMENT_ID/upload_sarif/
