name: Mega-Linter

on:
  push:
    branches: [master, release, develop]
  pull_request:
    branches: [master, release, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Mega-Linter
        uses: oxsecurity/megalinter@v5
        with:
          args: --report-output reports --sarif --formatters sarif
        env:
          DEFAULT_BRANCH: master

      - name: Check for SARIF Report
        run: |
          if [ ! -f reports/megalinter.sarif ]; then
            echo "SARIF report not found!"
            exit 1
          fi

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install DefectDojo API Client
        run: pip install defectdojo_api

      - name: Upload to DefectDojo
        run: python .github/workflows/upload_to_defectdojo.py
