name: CodeQL Analysis

on:
  push:
    branches:
      - master

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        languages: javascript, python  # Specify the languages you want to analyze
        query-languages: javascript   # Specify the CodeQL query language

    - name: Upload SARIF file
      uses: actions/upload-artifact@v2
      with:
        name: codeql-results
        path: ${{ github.workspace }}/codeql-bundle/codeql-sarif.sarif
